"""Add updated_at to messages

Revision ID: 13dec9ebcb5e
Revises: fix_bg_animation_enum
Create Date: 2025-12-31 23:33:07.862632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dec9ebcb5e'
down_revision = 'fix_bg_animation_enum'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###

