"""add_eme_phase_2_canvas_positioning_to_wall_photos

Revision ID: bfb4582d2806
Revises: e5240b7805da
Create Date: 2026-01-03 22:11:09.523057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb4582d2806'
down_revision = 'e5240b7805da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wall_photos', sa.Column('position_x', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('wall_photos', sa.Column('position_y', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('wall_photos', sa.Column('rotation', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('wall_photos', sa.Column('scale', sa.Float(), nullable=False, server_default=sa.text('1.0')))
    op.add_column('wall_photos', sa.Column('z_index', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('wall_photos', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('wall_photos', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wall_photos', 'height')
    op.drop_column('wall_photos', 'width')
    op.drop_column('wall_photos', 'z_index')
    op.drop_column('wall_photos', 'scale')
    op.drop_column('wall_photos', 'rotation')
    op.drop_column('wall_photos', 'position_y')
    op.drop_column('wall_photos', 'position_x')
    # ### end Alembic commands ###

