"""Add EME Phase 1: Wall invitations and upload control

Revision ID: e5240b7805da
Revises: 0fe353c8c613
Create Date: 2026-01-03 15:34:50.549912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5240b7805da'
down_revision = '0fe353c8c613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wall_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wall_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.String(), nullable=True),
    sa.Column('invited_name', sa.String(), nullable=True),
    sa.Column('invitation_type', sa.String(), nullable=False),
    sa.Column('invitation_code', sa.String(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wall_id'], ['birthday_walls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wall_invitations_id'), 'wall_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_wall_invitations_invitation_code'), 'wall_invitations', ['invitation_code'], unique=True)
    op.create_table('wall_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wall_id', sa.Integer(), nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=True),
    sa.Column('uploader_email', sa.String(), nullable=True),
    sa.Column('uploader_name', sa.String(), nullable=True),
    sa.Column('upload_type', sa.String(), nullable=False),
    sa.Column('upload_count', sa.Integer(), nullable=True),
    sa.Column('last_upload_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wall_id'], ['birthday_walls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wall_uploads_id'), 'wall_uploads', ['id'], unique=False)
    op.add_column('birthday_walls', sa.Column('uploads_enabled', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('birthday_walls', sa.Column('upload_permission', sa.String(), nullable=True, server_default='none'))
    op.add_column('birthday_walls', sa.Column('upload_paused', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('birthday_walls', sa.Column('is_sealed', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('birthday_walls', sa.Column('sealed_at', sa.DateTime(), nullable=True))
    op.alter_column('contact_submissions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('contact_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contact_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contact_submissions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('birthday_walls', 'sealed_at')
    op.drop_column('birthday_walls', 'is_sealed')
    op.drop_column('birthday_walls', 'upload_paused')
    op.drop_column('birthday_walls', 'upload_permission')
    op.drop_column('birthday_walls', 'uploads_enabled')
    op.drop_index(op.f('ix_wall_uploads_id'), table_name='wall_uploads')
    op.drop_table('wall_uploads')
    op.drop_index(op.f('ix_wall_invitations_invitation_code'), table_name='wall_invitations')
    op.drop_index(op.f('ix_wall_invitations_id'), table_name='wall_invitations')
    op.drop_table('wall_invitations')
    # ### end Alembic commands ###

